### ISSUE TITLE
Crashing with Incompatible Library Version

### ISSUE THREAD

**Issue by ryan-robeson** [ryan-robeson/homebrew-gimp#1]
Originally submitted by @dandroid88 on the resynthesizer repo

> Ryan, I just wanted to chime in and say thank you so much for putting this together.
> 
> I did run into a hickup, looks like something to do with the libgimp2.0 library version:

<details>
<summary> Crash Report</summary>
Process: resynthesizer [61768]
Path: /usr/local/Cellar/resynthesizer/2.0.3/share/gimp-plugins/resynthesizer/resynthesizer
Identifier: resynthesizer
Version: 0
Code Type: X86-64 (Native)
Parent Process: GIMP-bin [61749]
Responsible: resynthesizer [61768]
User ID: 501

Date/Time: 2019-06-25 16:39:12.736 -0700
OS Version: Mac OS X 10.14.5 (18F132)
Report Version: 12

Time Awake Since Boot: 710000 seconds
Time Since Wake: 11000 seconds

System Integrity Protection: disabled

Crashed Thread: 0

Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY

Termination Reason: DYLD, [0x3] Wrong version

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/Applications/GIMP.app/Contents/Resources/lib

Dyld Error Message:
Library not loaded: /usr/local/opt/libgimp2.0/lib/libgimpui-2.0.0.dylib
Referenced from: /usr/local/share/gimp-plugins/resynthesizer/resynthesizer
Reason: Incompatible library version: resynthesizer requires version 1001.0.0 or later, but libgimpui-2.0.0.dylib provides version 801.0.0

Binary Images:
0x102704000 - 0x10270fff7 +resynthesizer (0) <45E5E4B0-0AC9-3992-8264-08BE603AEBFD> /usr/local/share/gimp-plugins/resynthesizer/resynthesizer
0x1113b3000 - 0x11141d6ef dyld (655.1.1) /usr/lib/dyld

Model: MacBookPro11,3, BootROM 153.0.0.0.0, 4 processors, Intel Core i7, 2.3 GHz, 16 GB, SMC 2.19f12
Graphics: kHW_IntelIrisProItem, Intel Iris Pro, spdisplays_builtin
Graphics: kHW_NVidiaGeForceGTX750MItem, NVIDIA GeForce GT 750M, spdisplays_pcie_device, 2 GB
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x80AD, 0x484D54343147533641465238412D50422020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x134), Broadcom BCM43xx 1.0 (7.77.61.2 AirPortDriverBrcmNIC-1305.8)
Bluetooth: Version 6.0.12f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512F, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Apple Internal Keyboard / Trackpad
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 17.1
</details>

**Comment by ryan-robeson** [comment]
Hi @dandroid88, thanks again for reaching out.

Can you tell me exactly what steps you took to install resynthesizer?

**Comment by dandroid88** [comment]
I'll try my best to recall.

I had gimp installed previously (tbh, can't remember how I installed it as it was a while ago).
I had Homebrew installed already.

Then I followed your instructions:

`brew install ryan-robeson/gimp/resynthesizer`

Then:

> Go to Preferences > Folders > Plug-ins
> Add $(brew --prefix)/share/gimp-plugins/resynthesizer to the list
> The exact path is listed under Caveats after running brew install...
> Restart GIMP

**Comment by dandroid88** [comment]
Quick follow up:

The resolution was to

`brew cask install gimp`

Essentially, the older version of GIMP I had must have been installed via some other means.  I reviewed the notes [here](https://gist.github.com/ryan-robeson/5841f712ff23c910bbbfac793c16bfad) and noticed your command.  After running that, I have two side by side versions of GIMP and the newer one works with Resynthesizer.

Thanks again!

**Comment by ryan-robeson** [comment]
Wow, ok. Not sure I'd have thought of that. 

I assumed, wrongly apparently, that resynthesizer would use the libraries installed by Homebrew independently from the ones shipped with GIMP. 

Glad you got it figured out, and I appreciate you sharing your solution.
